name: 'Sync Github Repos To Gitee by https://blog.csdn.net/nuptaxin/article/details/124565474'

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: '名字随便起'
      uses: Yikun/hub-mirror-action@v1.1  # 使用Yikun/hub-mirror-action
      with:
        src: github/diaowinner  # 源端账户名(github)
        dst: gitee/diaowinner  # 目的端账户名(gitee)
        dst_key: ${{ secrets.SYNCPRIVATEKEY }}  # SSH密钥对中的私钥
        dst_token:  ${{ secrets.TOKEN }}  # Gitee账户的私人令牌
        account_type: user  # 账户类型
        clone_style: "https"  # 使用https方式进行clone，也可以使用ssh
        debug: true  # 启用后会显示所有执行命令
        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        static_list: "k8x12j"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
        timeout: '600s'  # git超时设置，超时后会自动重试git操作
